### ISSUE TITLE
Spellingsdingetjes enzo in de meldingen

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/Fix-Fixation-Output#7]
1. "**Tying to autodetect project folder(s)**" : **Tying** moet **Trying** zijn. (op zich is Tying wel een leuke woordspeling natuurlijk ;-))

2. .**JNF, .AGC, .AGS**: met kleine letters zijn: .agc, .ags
.JNF is inderdaad wel met hoofdletters (ergerlijke inconsistentie in Fixation)

3. **For example: "C:/Users/John Doe/project/result" or "[project]/result"\n"""**
realistischer voorbeelden:
*For example: "D:/Users/123456/EXP/result" or "EXP/result"\n"""

**Comment by tymees** [comment]
oops... Is als het goed is nu overal aangepast.

Geen idee hoe die Tying onstaan is :P

**Comment by irisopgithub** [comment]
nog eentje (laatste hoop ik):
**Trying to autodetect project folder(s)**
misschien duidelijker om daar van te maken:
**Trying to autodetect result folder(s) containing Fixation output files**
(want een project folder is al iets anders in het labjargon)

**Comment by tymees** [comment]
Yes, dat is een goed punt. Ik heb het aangepast
